apiVersion: apps/v1
kind: Deployment
metadata:
  name: xihe-statistics-deployment
  namespace: xihe-test-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xihe-statistics
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-perms-application.yml: "0600"
        vault.hashicorp.com/agent-inject-perms-postgre.crt: "0600"
        vault.hashicorp.com/agent-inject-perms-mq.crt: "0600"
        vault.hashicorp.com/agent-run-as-user: "5000"
        vault.hashicorp.com/agent-inject-secret-application.yml: "internal/data/mindspore/xihe-test-v2"
        vault.hashicorp.com/agent-inject-template-application.yml: |
          {{- with secret "internal/data/mindspore/xihe-test-v2" -}}
          {{ .Data.data.xiheStatistics }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-postgre.crt: "internal/data/mindspore/xihe-test-v2"
        vault.hashicorp.com/agent-inject-template-postgre.crt: |
          {{- with secret "internal/data/mindspore/xihe-test-v2" -}}
          {{ .Data.data.PostgreCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-mq.crt: "internal/data/mindspore/xihe-test-v2"
        vault.hashicorp.com/agent-inject-template-mq.crt: |
          {{- with secret "internal/data/mindspore/xihe-test-v2" -}}
          {{ .Data.data.MqCA }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: xihe-test
      labels:
        app: xihe-statistics
    spec:
      serviceAccount: xihe-test
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-statistics-test:c5ebfdafa8903c49ee050404b337ea517481c316
        imagePullPolicy: IfNotPresent
        args:
        - --port=8080
        - --config-file=/vault/secrets/application.yml
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        name: xihe-statistics
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
