apiVersion: apps/v1
kind: Deployment
metadata:
  name: async-server-deployment
  namespace: xihe-test-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: async-server
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-application.yml: 'internal/data/mindspore/xihe-test-v2'
        vault.hashicorp.com/agent-inject-perms-application.yml: "0600"
        vault.hashicorp.com/agent-inject-perms-postgre.crt: "0600"
        vault.hashicorp.com/agent-inject-perms-mq.crt: "0600"
        vault.hashicorp.com/agent-run-as-user: "5000"
        vault.hashicorp.com/agent-inject-template-application.yml: |
          {{- with secret "internal/data/mindspore/xihe-test-v2" -}}
          {{ .Data.data.asyncserver }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-postgre.crt: "internal/data/mindspore/xihe-test-v2"
        vault.hashicorp.com/agent-inject-template-postgre.crt: |
          {{- with secret "internal/data/mindspore/xihe-test-v2" -}}
          {{ .Data.data.PostgreCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-mq.crt: "internal/data/mindspore/xihe-test-v2"
        vault.hashicorp.com/agent-inject-template-mq.crt: |
          {{- with secret "internal/data/mindspore/xihe-test-v2" -}}
          {{ .Data.data.MqCA }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: xihe-test
      labels:
        app: async-server
    spec:
      serviceAccount: xihe-test
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-async-server:v1.0.20230420194635
        imagePullPolicy: IfNotPresent
        name: async-server
        args:
        - --port=8000
        - --config-file=/vault/secrets/application.yml
        - --enable_debug=true
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
