apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: secret-robot-token
spec:
  name: secret-robot-token
  keysMap:
    robot-token:
      path: secrets/data/mindspore/robot-github
      key: robot-openeuler-token
    app_id:
      path: secrets/data/mindspore/robot-github
      key: app_id
    app_secret:
      path: secrets/data/mindspore/robot-github
      key: app_secret
    robot-token-gitee:
      path: secrets/data/mindspore/robot-gitee
      key: robot-token
