---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xihe-server
  namespace: xihe-test-v2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xihe-server
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-perms-application.yml: "0600"
        vault.hashicorp.com/agent-inject-perms-ca.crt: "0600"
        vault.hashicorp.com/agent-inject-perms-redis.crt: "0600"
        vault.hashicorp.com/agent-inject-perms-postgre.crt: "0600"
        vault.hashicorp.com/agent-inject-perms-mq.crt: "0600"
        vault.hashicorp.com/agent-run-as-user: "5000"
        vault.hashicorp.com/agent-inject-secret-application.yml: "internal/data/mindspore/xihe-test-v2"
        vault.hashicorp.com/agent-inject-template-application.yml: |
          {{- with secret "internal/data/mindspore/xihe-test-v2" -}}
          {{ .Data.data.Server }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-ca.crt: "internal/data/mindspore/xihe-test-v2"
        vault.hashicorp.com/agent-inject-template-ca.crt: |
          {{- with secret "internal/data/mindspore/xihe-test-v2" -}}
          {{ .Data.data.MongoCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-redis.crt: "internal/data/mindspore/xihe-test-v2"
        vault.hashicorp.com/agent-inject-template-redis.crt: |
          {{- with secret "internal/data/mindspore/xihe-test-v2" -}}
          {{ .Data.data.RedisCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-postgre.crt: "internal/data/mindspore/xihe-test-v2"
        vault.hashicorp.com/agent-inject-template-postgre.crt: |
          {{- with secret "internal/data/mindspore/xihe-test-v2" -}}
          {{ .Data.data.PostgreCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-mq.crt: "internal/data/mindspore/xihe-test-v2"
        vault.hashicorp.com/agent-inject-template-mq.crt: |
          {{- with secret "internal/data/mindspore/xihe-test-v2" -}}
          {{ .Data.data.MqCA }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: xihe-test
      labels:
        app: xihe-server
    spec:
      serviceAccount: xihe-test
      containers:
      - name: xihe-server
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-server:97f347b62bf46f56cedb5886999fa8335b9fcefb
        imagePullPolicy: IfNotPresent
        args:
        - --port=8000
        - --config-file=/vault/secrets/application.yml
        - --enable_debug=true
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
